[package]
name = "net_shared"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
net_proc_macros = { workspace = true }

[lints]
workspace = true
